apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: polyglot-app
    service: loadgen
  name: loadgen
  namespace: polyglot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polyglot-app
      service: loadgen
  template:
    metadata:
      labels:
        app: polyglot-app
        service: loadgen
    spec:
      containers:
      - name: loadgen
        image: harbor.pdmodernapps.com/atrejomora/loadgen:latest
        imagePullPolicy: Always
        command:
        - "java"
        - "-jar"
        - "/loadgen.jar"
        - "shopping"
        - "50050"
        - "50051"
        - "2"
        - "15"
        - "0"
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
